name: easyy
description: iOS/Android App implemented using the Flutter SFK and Dart which makes it easier to comprehend English texts using intelligent word replacements, which reduce the difficulty of the text

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  fonts:
    - family: Abel
      fonts:
        - asset: fonts/Abel/Abel-Regular.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic

    - family: ReenieBeanie
      fonts:
        - asset: fonts/ReenieBeanie/ReenieBeanie-Regular.ttf

